version: "3"
services:
  backend:
    container_name: myportfolio-backend
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=__init__.py
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: flask run --host=0.0.0.0
    depends_on:
      - mysql

  frontend:
    container_name: myportfolio-frontend
    image: node:18
    working_dir: /frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules  # prevent host <-> container conflicts
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # useful for hot reloading in Docker

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
