version: "3.8"
services:
  frontend:
    container_name: myportfolio-frontend
    image: ghcr.io/davidbenj15/portfolio-frontend:latest
    ports:
      - "3000:80"

  caddy:
    container_name: caddy
    image: caddy:2
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend

volumes:
  mydatabase:
  caddy_data:
  caddy_config:
