version: "3"
services:
  backend:
    container_name: myportfolio-backend
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - FLASK_APP=__init__.py
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: flask run --host=0.0.0.0
    depends_on:
      - mysql

  frontend:
    container_name: myportfolio-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    # environment:
    #   - CHOKIDAR_USEPOLLING=true  # useful for hot reloading in Docker
  
  
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
  container_name: nginx
  image: jonasal/nginx-certbot
  restart: always
  environment:
    - CERTBOT_EMAIL=davidnbenjamin15@gmail.com
    - DHPARAM_SIZE=2048
    - RSA_KEY_SIZE=2048
    - DOMAINS=davidbenjamin.dev www.davidbenjamin.dev
    - CERTBOT_TEST_CERT=0  # Set to 1 for testing, 0 for production
    - STAGING=0  # Set to 1 for staging certificates
  ports:
    - 80:80
    - 443:443
  volumes:
    - nginx_secrets:/etc/letsencrypt
    - ./user_conf.d:/etc/nginx/user_conf.d
    - /var/lib/letsencrypt:/var/lib/letsencrypt
  depends_on:
    - backend
    - frontend

volumes:
  mydatabase:
  nginx_secrets:
  